services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: orders-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
    depends_on:
      - mysql
      - redis

  web:
    image: nginx:1.27-alpine
    container_name: orders-web
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: orders-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders_platform
      MYSQL_USER: orders
      MYSQL_PASSWORD: orders
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password","--sql-mode="]
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:7
    container_name: orders-redis
    ports:
      - "6379:6379"

  mailpit:
    image: axllent/mailpit:latest
    container_name: orders-mailpit
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP


  horizon:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    container_name: orders-horizon
    working_dir: /var/www/html
    command: bash -lc "php artisan horizon"
    volumes:
      - ./:/var/www/html
    depends_on:
      - app
      - redis

volumes:
  dbdata:
